ALTER TABLE payments
    ADD COLUMN IF NOT EXISTS type VARCHAR(50),
    ADD COLUMN IF NOT EXISTS plan VARCHAR(50),
    ADD COLUMN IF NOT EXISTS inv_id VARCHAR(64),
    ADD COLUMN IF NOT EXISTS response_package INTEGER;

CREATE UNIQUE INDEX IF NOT EXISTS uq_payments_inv_id ON payments(inv_id) WHERE inv_id IS NOT NULL;
